### ISSUE TITLE
Sjekk støtte for S-1 Salgsrapport v18

### ISSUE THREAD

**Issue by havwig** [AtB-AS/cleos#2]
Mail fra Stine Finskud Øgaard (stine.finskud.ogaard@entur.org):

> Som bruker av rapport S-1_Salgsdokumentasjon mottar dere denne eposten om ny versjon og hva som er nytt.
>
>Entur avregning (Cleos) har hatt behov for å få på plass en gjennomgående konsistent håndtering av MVA-informasjon i avregningsløsningen, standardisering av kolonnenavn i alle rapporter i tillegg til at feltene From/To Stop Place i S-1 rapporten nå inneholder Stop Place for periodebilletter hvis det er med i STS (Salget) til avregning (Celos). Dette gjorde vi i nye Cleos versjon 8.1 (produksjon 22.03.2021 kl 11) og Versjon 8.2  (produksjon 30.04.2021). S-1 Salgsdokumentasjonen daglig endres fra versjon 15/17 til versjon 18.
>
>Det rapporteres i dag flere MVA-verdier med subtile forskjeller på hva de representerer. Problemstillingen er særlig tydelig ved endringene i MVA-sats på samme kode midt i året, noe som har skjedd i forbindelse med COVID. Det gjelder også avregning og rapportering på data som ikke har korrekt eller mangler helt MVA-informasjon. Vi innfører to begreper i avregningen: LOKAL MVA-kode og STANDARD MVA-kode, dette er begreper vi låner fra SAF-T spesifikasjonen. Lokal MVA-kode er en kode som kan settes av selskapet som mappes mot standardkode (dvs hvert selskap kan ha hver sin lokale MVA-kode). Standard MVA-kode er den standardisert MVA-kode som forvaltes av Skatteetaten.
>
>Det er også i versjon 18 en del felter som har endret navn men som har samme innhold/verdi i feltet. Denne endringen er knyttet til behovet for standardisering navn på verdien feltet representer i alle rapporter.
>
>Ved salg av periodebilletter vil rapporten nå vise From/To Stope Places, når det er med i salgstransaksjonen til avregning (Cleos).
>
>Er det produsert test data i Staging, vil dere kunne verifisere endringen i Staging.
>
>Vi setter ny versjon S-1 Salgsdokumentasjon_V18 opp i produksjon i dag, slik at Versjon 17 og 18 kjøres parallelt til neste månedslutt (mai/juni). Etter den tid stoppes versjon 17 og evt. eldre versjoner, hvis vi ikke har mottatt noen tilbakemelding om at det blir vanskelig for noen av dere som bruker en gml. rapport.
>
>Vi anbefaler alle å ta i bruk de nyeste versjonene av rapportene, de gamle rapportene vil ikke bli vedlikeholdt.

Vi må i første omgang teste med v18, så finne ut av hvilke tilpassinger som må gjøres.

**Comment by torfjor** [comment]
@havwig we just push the csv to AtBs ftp.

Morten W. needs to update the schema. Send him an example from the bucket.
